export let API_URL = "API_URL_REPLACE_ME";
export let ATUALIZACAO_CADASTRAL_URL = "ATUALIZACAO_CADASTRAL_URL_REPLACE_ME";

if (process.env.NODE_ENV === "development") {
  API_URL = process.env.REACT_APP_API_URL;
  ATUALIZACAO_CADASTRAL_URL = process.env.REACT_APP_ATUALIZACAO_CADASTRAL_URL;
}
